site_name: Brain Segmentation
site_description: Documentation for the Brain Segmentation project
site_author: Brain Segmentation Team

# Repository information
repo_name: BrainSegmentation
repo_url: https://github.com/halirutan/BrainSegmentation
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Brain Segmentation Team

# Configuration
theme:
  name: readthedocs

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

# Navigation structure
nav:
  - Home: index.md
  - Installation: installation.md
  - Contributing:
      - Overview: contribute/contributing.md
      - Writing Documentation: contribute/howto_write_docs.md
      - Writing Code: contribute/howto_write_code.md
  - Creating Training Data:
      - General Approach: training_data/overview.md
      - CHARM Segmentation: training_data/charm.md
      - SynthSeg Segmentation: training_data/synth_seg.md
      - FullHeadSeg: training_data/FullHeadSeg.md
  - Automatic Code Documentation:
    - API Reference: api.md

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ src ]
          options:
            docstring_style: google
            show_source: true
