site_name: Brain Segmentation
site_description: Documentation for the Brain Segmentation project
site_author: Brain Segmentation Team

# Repository information
repo_name: BrainSegmentation
repo_url: https://github.com/halirutan/BrainSegmentation
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Brain Segmentation Team

# Configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - Examples: examples.md
  - API Reference: api_reference.md
  - Contributing: contributing.md
  - License: license.md

# Plugins
plugins:
  - search

# Extra settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/BrainSegmentation
  version:
    provider: mike